[package]
name = "discord_data_markov_chain"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
markov = "1.1"
csv = "1.1"
serde = "1.0"
serde_derive = "1.0"
walkdir = "2.3"
pbr = "1.0"
clap = "2.33"
